db.url=jdbc:mysql://ballast.proxy.rlwy.net:49937/gestion_medical?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=BjRiAtgFXwPGefkletBgNAFyHFaoBcIU
hikari.maximumPoolSize=10
hikari.minimumIdle=2
hikari.connectionTimeout=30000
hikari.maxLifetime=600000
hikari.keepaliveTime=300000